CREATE DATABASE BD_MILLENNIUM_BANK;

USE BD_MILLENNIUM_BANK;

CREATE TABLE BANCO(

COD					INT				AUTO_INCREMENT	PRIMARY KEY,
COD_BANCO			INT				NOT NULL		UNIQUE,
NOME				VARCHAR(100)	NOT NULL,
CNPJ				CHAR(14)		NOT NULL
);

CREATE TABLE AGENCIA(

COD					INT				AUTO_INCREMENT	PRIMARY KEY,
COD_BANCO			INT				NOT NULL,
NUMERO				INT				NOT NULL		UNIQUE,
BAIRRO				VARCHAR(50)		NOT NULL
);

CREATE TABLE CONTA(

COD					INT				AUTO_INCREMENT	PRIMARY KEY,
BANCO				VARCHAR(50)		NOT NULL,
NUMERO				INT				NOT NULL		UNIQUE,
TIPO_CONTA			VARCHAR(15)		NOT NULL,
SALDO				DECIMAL(8,2)	NOT NULL,
COD_AGENCIA			INT				NOT NULL,
COD_CLIENTE			INT				NOT NULL
);

CREATE TABLE CLIENTE(

COD					INT				AUTO_INCREMENT	PRIMARY KEY,
SEXO				VARCHAR(9)		NOT NULL,
NOME				VARCHAR(100)	NOT NULL,
ESTADO_CIVIL		VARCHAR(8)		NOT NULL,
RG					CHAR(9)			NOT NULL		UNIQUE,
CPF					CHAR(11)		NOT NULL		UNIQUE,
TEL_FIXO			CHAR(10)		NOT NULL,
TEL_COMERCIAL		VARCHAR(11)		NOT NULL,
CELULAR				CHAR(11)		NOT NULL,
LOGRADOURO			VARCHAR(50)		NOT NULL,
NUMERO				INT				NOT NULL,
BAIRRO				VARCHAR(50)		NOT NULL,
CIDADE				VARCHAR(50)		NOT NULL,
UF					CHAR(2)			NOT NULL,
EMAIL				VARCHAR(70)		NOT NULL		UNIQUE
);

CREATE TABLE USUARIOS(
COD					INT				AUTO_INCREMENT	PRIMARY KEY,
USUARIO				VARCHAR(10)		NOT NULL		UNIQUE,
SENHA				VARCHAR(20)		NOT NULL
);

ALTER TABLE AGENCIA
ADD CONSTRAINT BAN_AGE FOREIGN KEY(COD_BANCO)
REFERENCES BANCO(COD);

ALTER TABLE CONTA
ADD CONSTRAINT AGE_CON FOREIGN KEY(COD_AGENCIA)
REFERENCES AGENCIA(COD);

ALTER TABLE CONTA
ADD CONSTRAINT AGE_CLI FOREIGN KEY(COD_CLIENTE)
REFERENCES CLIENTE(COD);

CREATE UNIQUE INDEX NO_TIPO_Ban ON CONTA (COD_CLIENTE ASC, TIPO_CONTA ASC, BANCO ASC);

INSERT INTO USUARIOS(USUARIO, SENHA) VALUES('ADMIN', 'abc123');